version: '3.9'  # 明确指定 Compose 文件版本

services:
  zerocat:
    container_name: zerocat
    image: zerocat:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped  # 推荐值，更安全
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://root:123456@127.0.0.1:3557/zerocat_develop
