/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/[username]/': RouteRecordInfo<'/[username]/', '/:username', { username: ParamValue<true> }, {
      username: ParamValue<false>
    }>,
    '/[username]/[projectname]/': RouteRecordInfo<'/[username]/[projectname]/', '/:username/:projectname', {
      username: ParamValue<true>,
      projectname: ParamValue<true>
    }, { username: ParamValue<false>, projectname: ParamValue<false> }>,
    '/[username]/[projectname]/branches': RouteRecordInfo<'/[username]/[projectname]/branches', '/:username/:projectname/branches', {
      username: ParamValue<true>,
      projectname: ParamValue<true>
    }, { username: ParamValue<false>, projectname: ParamValue<false> }>,
    '/[username]/[projectname]/editor': RouteRecordInfo<'/[username]/[projectname]/editor', '/:username/:projectname/editor', {
      username: ParamValue<true>,
      projectname: ParamValue<true>
    }, { username: ParamValue<false>, projectname: ParamValue<false> }>,
    '/[username]/[projectname]/fork': RouteRecordInfo<'/[username]/[projectname]/fork', '/:username/:projectname/fork', {
      username: ParamValue<true>,
      projectname: ParamValue<true>
    }, { username: ParamValue<false>, projectname: ParamValue<false> }>,
    '/[username]/[projectname]/push': RouteRecordInfo<'/[username]/[projectname]/push', '/:username/:projectname/push', {
      username: ParamValue<true>,
      projectname: ParamValue<true>
    }, { username: ParamValue<false>, projectname: ParamValue<false> }>,
    '/[username]/[projectname]/settings': RouteRecordInfo<'/[username]/[projectname]/settings', '/:username/:projectname/settings', {
      username: ParamValue<true>,
      projectname: ParamValue<true>
    }, { username: ParamValue<false>, projectname: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/app/account/': RouteRecordInfo<'/app/account/', '/app/account', Record<never, never>, Record<never, never>>,
    '/app/account/callback': RouteRecordInfo<'/app/account/callback', '/app/account/callback', Record<never, never>, Record<never, never>>,
    '/app/account/email/': RouteRecordInfo<'/app/account/email/', '/app/account/email', Record<never, never>, Record<never, never>>,
    '/app/account/email/verify': RouteRecordInfo<'/app/account/email/verify', '/app/account/email/verify', Record<never, never>, Record<never, never>>,
    '/app/account/login': RouteRecordInfo<'/app/account/login', '/app/account/login', Record<never, never>, Record<never, never>>,
    '/app/account/logout': RouteRecordInfo<'/app/account/logout', '/app/account/logout', Record<never, never>, Record<never, never>>,
    '/app/account/magiclink/': RouteRecordInfo<'/app/account/magiclink/', '/app/account/magiclink', Record<never, never>, Record<never, never>>,
    '/app/account/magiclink/validate': RouteRecordInfo<'/app/account/magiclink/validate', '/app/account/magiclink/validate', Record<never, never>, Record<never, never>>,
    '/app/account/oauth/': RouteRecordInfo<'/app/account/oauth/', '/app/account/oauth', Record<never, never>, Record<never, never>>,
    '/app/account/oauth/bind/error': RouteRecordInfo<'/app/account/oauth/bind/error', '/app/account/oauth/bind/error', Record<never, never>, Record<never, never>>,
    '/app/account/oauth/bind/success': RouteRecordInfo<'/app/account/oauth/bind/success', '/app/account/oauth/bind/success', Record<never, never>, Record<never, never>>,
    '/app/account/oauth/callback': RouteRecordInfo<'/app/account/oauth/callback', '/app/account/oauth/callback', Record<never, never>, Record<never, never>>,
    '/app/account/register/': RouteRecordInfo<'/app/account/register/', '/app/account/register', Record<never, never>, Record<never, never>>,
    '/app/account/register/verify': RouteRecordInfo<'/app/account/register/verify', '/app/account/register/verify', Record<never, never>, Record<never, never>>,
    '/app/account/relationships': RouteRecordInfo<'/app/account/relationships', '/app/account/relationships', Record<never, never>, Record<never, never>>,
    '/app/account/retrieve': RouteRecordInfo<'/app/account/retrieve', '/app/account/retrieve', Record<never, never>, Record<never, never>>,
    '/app/account/retrievecallback': RouteRecordInfo<'/app/account/retrievecallback', '/app/account/retrievecallback', Record<never, never>, Record<never, never>>,
    '/app/account/totp/': RouteRecordInfo<'/app/account/totp/', '/app/account/totp', Record<never, never>, Record<never, never>>,
    '/app/account/totp/add': RouteRecordInfo<'/app/account/totp/add', '/app/account/totp/add', Record<never, never>, Record<never, never>>,
    '/app/admin/config': RouteRecordInfo<'/app/admin/config', '/app/admin/config', Record<never, never>, Record<never, never>>,
    '/app/debug/api': RouteRecordInfo<'/app/debug/api', '/app/debug/api', Record<never, never>, Record<never, never>>,
    '/app/debug/editor': RouteRecordInfo<'/app/debug/editor', '/app/debug/editor', Record<never, never>, Record<never, never>>,
    '/app/debug/token': RouteRecordInfo<'/app/debug/token', '/app/debug/token', Record<never, never>, Record<never, never>>,
    '/app/editor': RouteRecordInfo<'/app/editor', '/app/editor', Record<never, never>, Record<never, never>>,
    '/app/explore/': RouteRecordInfo<'/app/explore/', '/app/explore', Record<never, never>, Record<never, never>>,
    '/app/link/project': RouteRecordInfo<'/app/link/project', '/app/link/project', Record<never, never>, Record<never, never>>,
    '/app/link/user': RouteRecordInfo<'/app/link/user', '/app/link/user', Record<never, never>, Record<never, never>>,
    '/app/new': RouteRecordInfo<'/app/new', '/app/new', Record<never, never>, Record<never, never>>,
    '/app/notifications': RouteRecordInfo<'/app/notifications', '/app/notifications', Record<never, never>, Record<never, never>>,
    '/app/project': RouteRecordInfo<'/app/project', '/app/project', Record<never, never>, Record<never, never>>,
    '/app/projectlist/': RouteRecordInfo<'/app/projectlist/', '/app/projectlist', Record<never, never>, Record<never, never>>,
    '/app/projectlist/[id]': RouteRecordInfo<'/app/projectlist/[id]', '/app/projectlist/:id', {
      id: ParamValue<true>
    }, { id: ParamValue<false> }>,
    '/app/proxy/': RouteRecordInfo<'/app/proxy/', '/app/proxy', Record<never, never>, Record<never, never>>,
    '/app/proxy/[id]/': RouteRecordInfo<'/app/proxy/[id]/', '/app/proxy/:id', { id: ParamValue<true> }, {
      id: ParamValue<false>
    }>,
    '/app/proxy/explore': RouteRecordInfo<'/app/proxy/explore', '/app/proxy/explore', Record<never, never>, Record<never, never>>,
    '/app/proxy/news': RouteRecordInfo<'/app/proxy/news', '/app/proxy/news', Record<never, never>, Record<never, never>>,
    '/app/proxy/open': RouteRecordInfo<'/app/proxy/open', '/app/proxy/open', Record<never, never>, Record<never, never>>,
    '/app/proxy/search': RouteRecordInfo<'/app/proxy/search', '/app/proxy/search', Record<never, never>, Record<never, never>>,
    '/app/proxy/studios/[id]': RouteRecordInfo<'/app/proxy/studios/[id]', '/app/proxy/studios/:id', {
      id: ParamValue<true>
    }, { id: ParamValue<false> }>,
    '/app/proxy/user/[username]': RouteRecordInfo<'/app/proxy/user/[username]', '/app/proxy/user/:username', {
      username: ParamValue<true>
    }, { username: ParamValue<false> }>,
    '/app/search': RouteRecordInfo<'/app/search', '/app/search', Record<never, never>, Record<never, never>>,
    '/app/tools/asdm': RouteRecordInfo<'/app/tools/asdm', '/app/tools/asdm', Record<never, never>, Record<never, never>>,
    '/app/tools/comparer': RouteRecordInfo<'/app/tools/comparer', '/app/tools/comparer', Record<never, never>, Record<never, never>>,
    '/app/ui/test': RouteRecordInfo<'/app/ui/test', '/app/ui/test', Record<never, never>, Record<never, never>>,
  }
}
