version: "3"
services:
  meilisync-admin:
    image: ghcr.io/long2ice/meilisync-admin/meilisync-admin
    container_name: meilisync-admin
    restart: always
    networks:
      - meilisync-net
    ports:
      - 7701:8000
    environment:
      - DB_URL=mysql://root:123456@host.docker.internal:3557/meilisync_admin  # 可选：如果你后续不使用 MySQL 可移除
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=secret
      - SENTRY_DSN=

  redis:
    image: redis:7
    container_name: redis
    restart: always
    networks:
      - meilisync-net

networks:
  meilisync-net:
    driver: bridge
