name: Sync Fork

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v2.0.10
        with:
          owner: sunwuyuan
          base: main
          head: main
          repo: zerocat
